import { StyleSheet } from 'react-native';
import type { ColorScheme } from '@/theme';
import { BORDER_RADIUS } from '@/theme/constants';

export const createProviderStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    providerCategoryTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text.secondary,
      marginTop: 16,
      marginBottom: 8,
    },
    providerCard: {
      backgroundColor: colors.background.darkCard,
      padding: 16,
      borderRadius: BORDER_RADIUS.md,
      marginBottom: 12,
    },
    providerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    providerTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    providerName: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text.primary,
    },
    primaryBadge: {
      backgroundColor: colors.brand.primary,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: BORDER_RADIUS.xs,
    },
    primaryBadgeText: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.text.primary,
    },
    fallbackBadge: {
      backgroundColor: colors.text.tertiary + '30',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: BORDER_RADIUS.xs,
    },
    fallbackBadgeText: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.text.tertiary,
    },
    configSection: {
      backgroundColor: colors.background.primary,
      padding: 12,
      borderRadius: BORDER_RADIUS.sm,
      marginBottom: 12,
    },
    configSectionTitle: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.text.secondary,
      marginBottom: 8,
    },
    configRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 4,
    },
    configLabel: {
      fontSize: 12,
      color: colors.text.tertiary,
    },
    configValue: {
      fontSize: 12,
      color: colors.text.primary,
      fontWeight: '500',
      flex: 1,
      textAlign: 'right',
    },
    actionRow: {
      flexDirection: 'row',
      gap: 8,
    },
    testButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.background.secondary,
      paddingVertical: 10,
      borderRadius: BORDER_RADIUS.sm,
    },
    testButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text.primary,
    },
    editButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.brand.primary,
      paddingVertical: 10,
      borderRadius: BORDER_RADIUS.sm,
    },
    editButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text.primary,
    },
    setPrimaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.brand.primary + '20',
      borderWidth: 1,
      borderColor: colors.brand.primary,
      paddingVertical: 10,
      borderRadius: BORDER_RADIUS.sm,
    },
    setPrimaryButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.brand.primary,
    },
    testResult: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 12,
      padding: 8,
      backgroundColor: colors.background.primary,
      borderRadius: 6,
    },
    testResultText: {
      fontSize: 12,
      flex: 1,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.background.secondary,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: '90%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.muted,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text.primary,
    },
    modalBody: {
      padding: 16,
      maxHeight: 500,
    },
    formSection: {
      marginBottom: 24,
    },
    formSectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text.secondary,
      marginBottom: 12,
    },
    formField: {
      marginBottom: 16,
    },
    formLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.text.primary,
      marginBottom: 4,
    },
    formHint: {
      fontSize: 11,
      color: colors.text.tertiary,
      marginBottom: 6,
    },
    textInput: {
      backgroundColor: colors.background.darkCard,
      borderRadius: BORDER_RADIUS.sm,
      padding: 12,
      fontSize: 14,
      color: colors.text.primary,
      borderWidth: 1,
      borderColor: colors.border.muted,
    },
    selectInput: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.background.darkCard,
      borderRadius: BORDER_RADIUS.sm,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border.muted,
    },
    selectInputText: {
      fontSize: 14,
      color: colors.text.primary,
    },
    pickerDropdown: {
      backgroundColor: colors.background.darkCard,
      borderRadius: BORDER_RADIUS.sm,
      marginTop: 4,
      borderWidth: 1,
      borderColor: colors.border.muted,
    },
    pickerOption: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.muted,
    },
    pickerOptionSelected: {
      backgroundColor: colors.brand.primary + '30',
    },
    pickerOptionText: {
      fontSize: 14,
      color: colors.text.primary,
    },
    pickerOptionTextSelected: {
      fontWeight: '600',
    },
    formFieldRow: {
      flexDirection: 'row',
      gap: 16,
    },
    toggleField: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.background.darkCard,
      padding: 12,
      borderRadius: BORDER_RADIUS.sm,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: 12,
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border.muted,
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: BORDER_RADIUS.sm,
      backgroundColor: colors.background.darkCard,
      alignItems: 'center',
    },
    cancelButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text.secondary,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: BORDER_RADIUS.sm,
      backgroundColor: colors.brand.primary,
      alignItems: 'center',
    },
    saveButtonDisabled: {
      opacity: 0.6,
    },
    saveButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text.primary,
    },
    errorMessage: {
      fontSize: 12,
      color: colors.semantic.error,
      textAlign: 'center',
      padding: 8,
    },
    modelValueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
      justifyContent: 'flex-end',
    },
    costBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: BORDER_RADIUS.xs,
    },
    costBadgeText: {
      fontSize: 10,
      fontWeight: '700',
    },
    modelSelectContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    modelOptionContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modelOptionMain: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    recommendedBadge: {
      backgroundColor: colors.brand.primary + '30',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: BORDER_RADIUS.xs,
    },
    recommendedBadgeText: {
      fontSize: 9,
      fontWeight: '600',
      color: colors.brand.primary,
    },
    modelDescription: {
      fontSize: 11,
      color: colors.text.tertiary,
      marginTop: 4,
    },
    qualityButtonRow: {
      flexDirection: 'row',
      gap: 12,
    },
    qualityButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: BORDER_RADIUS.sm,
      backgroundColor: colors.background.darkCard,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border.muted,
    },
    qualityButtonSelected: {
      backgroundColor: colors.brand.primary + '30',
      borderColor: colors.brand.primary,
    },
    qualityButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text.secondary,
    },
    qualityButtonTextSelected: {
      color: colors.brand.primary,
      fontWeight: '600',
    },
    refreshButton: {
      padding: 8,
      borderRadius: 6,
      backgroundColor: colors.background.primary,
    },
    syncInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border.muted,
    },
    syncInfoText: {
      fontSize: 11,
      color: colors.text.tertiary,
    },
    cachedBadge: {
      backgroundColor: colors.brand.primary + '20',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: BORDER_RADIUS.xs,
      marginLeft: 8,
    },
    cachedBadgeText: {
      fontSize: 9,
      fontWeight: '600',
      color: colors.brand.primary,
    },
  });
