#!/bin/bash
# Auto-generated Docker Environment Setup Script
# Generated at: 2025-12-04T10:05:37.729Z
# Source: packages/platform-core/src/config/services-definition.ts
#
# DO NOT EDIT THIS FILE MANUALLY
# Regenerate with: npm run generate:config

echo "🔧 Setting up Docker environment variables from unified port configuration..."

# Backend Services
export SYSTEM_SERVICE_PORT=3001
export STORAGE_SERVICE_PORT=3002
export USER_SERVICE_PORT=3003
export AI_CONFIG_SERVICE_PORT=3004
export AI_CONTENT_SERVICE_PORT=3005
export AI_ANALYTICS_SERVICE_PORT=3006
export MUSIC_SERVICE_PORT=3007
export API_GATEWAY_PORT=8080

# Frontend Apps
export AIPONGE_PORT=3020

# Metro Bundlers
export AIPONGE_METRO_PORT=8082

# Infrastructure
export POSTGRESQL_PORT=5432
export REDIS_PORT=6379

echo "✅ Docker environment variables configured successfully!"
echo ""
echo "🚀 Available backend services:"
echo "   system-service: \$SYSTEM_SERVICE_PORT"
echo "   storage-service: \$STORAGE_SERVICE_PORT"
echo "   user-service: \$USER_SERVICE_PORT"
echo "   ai-config-service: \$AI_CONFIG_SERVICE_PORT"
echo "   ai-content-service: \$AI_CONTENT_SERVICE_PORT"
echo "   ai-analytics-service: \$AI_ANALYTICS_SERVICE_PORT"
echo "   music-service: \$MUSIC_SERVICE_PORT"
echo "   api-gateway: \$API_GATEWAY_PORT"
echo ""
echo "🎨 Available frontend applications:"
echo "   aiponge: \$AIPONGE_PORT"
echo ""
echo "📦 Metro bundlers:"
echo "   aiponge-metro: \$AIPONGE_METRO_PORT"
echo ""
echo "🔧 Infrastructure services:"
echo "   postgresql: \$POSTGRESQL_PORT"
echo "   redis: \$REDIS_PORT"
